version: "2"
linters:
  default: none
  enable:
    - dupl
    - gochecknoinits
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - gocyclo
    - nestif
    - testifylint
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy
        - singleCaseSwitch
        - ifElseChain
      enabled-tags:
        - performance
        - style
        - experimental
    lll: { line-length: 140 }
    misspell: { locale: US }
  exclusions:
    generated: lax
    rules:
      - linters: [revive]
        text: 'package-comments: should have a package comment'
      - linters: [dupl, gosec]
        path: _test\.go
      - linters: [revive, unused]
        path: _test\.go$
        text: unused-parameter
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$