# https://taskfile.dev

version: '3'

includes:
  example: { taskfile: _example/Taskfile.yml }

env:
  GO_MODULE: github.com/Semior001/groxy

tasks:
  install:
    desc: "builds and install local groxy version"
    cmd: |
      GROXY_VERSION=$(git describe --tags --long)
      go install -ldflags "-X 'main.version=$GROXY_VERSION-local' -s -w" ./cmd/...

  check:
    desc: "run all CI/CD checks"
    deps:
      - test
      - lint

  run:
    desc: "run application from local source"
    cmd: |
      go run -ldflags "-X 'main.version=local'" ./cmd/groxy {{.CLI_ARGS}}

  lint:
    desc: "lint"
    cmd: |
      go tool -modfile=tools/golangci-lint/go.mod \
        golangci-lint run \
          --timeout 5m \
          --issues-exit-code 1 \
          --config .golangci.yml ./...

  test:
    desc: "run tests"
    cmd: |
      go test -race -count=1 ./...

  bench:
    desc: "run benchmarks with ghz"
    deps:
      - bench:mocker
      - bench:reverse-proxy
      - bench:templated
      - bench:request-matcher
      - bench:complex-request-matcher

  bench:server:
    desc: "run grpc-echo server for manual tests"
    cmds:
      - cmd: docker run -d --rm -p 8081:8080 semior/grpc-echo:latest
      - defer: docker stop $(docker ps -q --filter ancestor=semior/grpc-echo:latest)
      - go run -ldflags "-X 'main.version=local'" ./cmd/groxy --reflection --file.name="_example/benchmark.yaml" {{.CLI_ARGS}}

  bench:mocker:
    desc: "run benchmarks for the mocking functionality"
    vars:
      HOST: "localhost:8080"
      COUNT: "10000"
    cmd: |
      ghz --insecure \
        --metadata '{"test": "mocker"}' \
        --call 'grpc_echo/v1/EchoService/Echo' \
        -d '{"ping": "mocker"}' -c 1 --total {{.COUNT}} {{.HOST}}

  bench:reverse-proxy:
    desc: "run benchmarks for reverse proxy functionality"
    vars:
      HOST: "localhost:8080"
      COUNT: "10000"
    cmd: |
      ghz --insecure \
        --metadata '{"test": "reverse-proxy"}' \
        --call 'grpc_echo/v1/EchoService/Echo' \
        -d '{"ping": "reverse-proxy"}' -c 1 --total {{.COUNT}} {{.HOST}}

  bench:templater:
    desc: "run benchmarks for templated response functionality"
    vars:
      HOST: "localhost:8080"
      COUNT: "10000"
    cmd: |
      ghz --insecure \
        --metadata '{"test": "templated"}' \
        --call 'grpc_echo/v1/EchoService/Echo' \
        -d '{"ping": "templated"}' -c 1 --total {{.COUNT}} {{.HOST}}

  bench:request-matcher:
    desc: "run benchmarks for request body matching functionality"
    vars:
      HOST: "localhost:8080"
      COUNT: "10000"
    cmd: |
      ghz --insecure \
        --call 'grpc_echo/v1/EchoService/Echo' \
        -d '{"ping": "request-matcher"}' -c 1 --total {{.COUNT}} {{.HOST}}

  bench:complex-request-matcher:
    desc: "run benchmarks for request body matching functionality"
    vars:
      HOST: "localhost:8080"
      COUNT: "10000"
    cmd: |
      ghz --insecure \
        --call 'grpc_echo/v1/EchoService/Echo' \
        -d '{"ping": "complex-request-matcher"}' -c 1 --total {{.COUNT}} {{.HOST}}

  gen:
    desc: "generate all"
    deps:
      - gen:jsonschema
      - gen:example
      - gen:annotation
      - gen:testdata

  gen:jsonschema:
    desc: "generate jsonschema"
    cmd: |
      go run ./cmd/jsonschemagen \
        --title "gRoxy Configuration Schema" \
        --description "JSON schema for gRoxy proxy configuration files" \
        --schema-version "https://json-schema.org/draft/2020-12/schema" \
        --id "https://raw.githubusercontent.com/Semior001/groxy/refs/heads/master/schema.json" \
        --output schema.json \
        {{.CLI_ARGS}}

  gen:annotation:
    desc: "generate annotation"
    cmd: |
      protoc --go_out=./groxypb --go_opt=module=$GO_MODULE/groxypb ./groxypb/*.proto

  gen:example:
    desc: "generate example"
    cmd: |
      protoc \
        --go_out=./_example --go_opt=module=$GO_MODULE/_example \
        --go-grpc_out=./_example --go-grpc_opt=module=$GO_MODULE/_example \
        ./_example/*.proto

  gen:testdata:
    desc: "generate testdata"
    cmd: |
      protoc \
        --go_out=./pkg/protodef/testdata --go_opt=module=$GO_MODULE/pkg/protodef/testdata \
        --go-grpc_out=./pkg/protodef/testdata --go-grpc_opt=module=$GO_MODULE/pkg/protodef/testdata \
        ./pkg/protodef/testdata/*.gen.proto
      protoc \
        --go_out=./pkg/grpcx/grpctest --go_opt=module=$GO_MODULE/pkg/grpcx/grpctest \
        --go-grpc_out=./pkg/grpcx/grpctest --go-grpc_opt=module=$GO_MODULE/pkg/grpcx/grpctest \
        ./pkg/grpcx/grpctest/*.proto