// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package discovery

import (
	"context"
	"sync"
)

// Ensure, that ProviderMock does implement Provider.
// If this is not the case, regenerate this file with moq.
var _ Provider = &ProviderMock{}

// ProviderMock is a mock implementation of Provider.
//
// 	func TestSomethingThatUsesProvider(t *testing.T) {
//
// 		// make and configure a mocked Provider
// 		mockedProvider := &ProviderMock{
// 			EventsFunc: func(ctx context.Context) <-chan string {
// 				panic("mock out the Events method")
// 			},
// 			NameFunc: func() string {
// 				panic("mock out the Name method")
// 			},
// 			StateFunc: func(ctx context.Context) (*State, error) {
// 				panic("mock out the State method")
// 			},
// 		}
//
// 		// use mockedProvider in code that requires Provider
// 		// and then make assertions.
//
// 	}
type ProviderMock struct {
	// EventsFunc mocks the Events method.
	EventsFunc func(ctx context.Context) <-chan string

	// NameFunc mocks the Name method.
	NameFunc func() string

	// StateFunc mocks the State method.
	StateFunc func(ctx context.Context) (*State, error)

	// calls tracks calls to the methods.
	calls struct {
		// Events holds details about calls to the Events method.
		Events []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// State holds details about calls to the State method.
		State []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockEvents sync.RWMutex
	lockName   sync.RWMutex
	lockState  sync.RWMutex
}

// Events calls EventsFunc.
func (mock *ProviderMock) Events(ctx context.Context) <-chan string {
	if mock.EventsFunc == nil {
		panic("ProviderMock.EventsFunc: method is nil but Provider.Events was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockEvents.Lock()
	mock.calls.Events = append(mock.calls.Events, callInfo)
	mock.lockEvents.Unlock()
	return mock.EventsFunc(ctx)
}

// EventsCalls gets all the calls that were made to Events.
// Check the length with:
//     len(mockedProvider.EventsCalls())
func (mock *ProviderMock) EventsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockEvents.RLock()
	calls = mock.calls.Events
	mock.lockEvents.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *ProviderMock) Name() string {
	if mock.NameFunc == nil {
		panic("ProviderMock.NameFunc: method is nil but Provider.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//     len(mockedProvider.NameCalls())
func (mock *ProviderMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// State calls StateFunc.
func (mock *ProviderMock) State(ctx context.Context) (*State, error) {
	if mock.StateFunc == nil {
		panic("ProviderMock.StateFunc: method is nil but Provider.State was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockState.Lock()
	mock.calls.State = append(mock.calls.State, callInfo)
	mock.lockState.Unlock()
	return mock.StateFunc(ctx)
}

// StateCalls gets all the calls that were made to State.
// Check the length with:
//     len(mockedProvider.StateCalls())
func (mock *ProviderMock) StateCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockState.RLock()
	calls = mock.calls.State
	mock.lockState.RUnlock()
	return calls
}
