# https://taskfile.dev

version: '3'

vars:
  CONFIG: '{{.CONFIG | default "_example/header-matching/config.yaml"}}'

tasks:
  server:
    desc: start the example server with a given config (default: header-matching)
    summary: |
      starts the example server on port 8080.
      pass CONFIG to use a different example config, e.g.:
        task server CONFIG=_example/upstream-forwarding/config.yaml
    cmd: |
      go run -ldflags "-X 'main.version=local'" ./cmd/groxy \
        --file.name='{{.CONFIG}}' --signature --debug --reflection \
        {{.CLI_ARGS}}

  stub-with-header:
    desc: >-
      make a request to stub method with header 'test: true', see summary for details
    summary: |
      requires: task server CONFIG=_example/header-matching/config.yaml
      response will be: {"message": "needed value received","code": 200}
    cmd: |
      grpcurl -plaintext -proto '_example/service.proto' \
        -H 'test: true' \
        -d '{"message":"needed value"}' \
        {{.CLI_ARGS}} \
        localhost:8080 com.github.Semior001.groxy.example.mock.ExampleService/Stub

  stub-with-body:
    desc: make a request to stub method matching body value, see summary for details
    summary: |
      requires: task server CONFIG=_example/body-matching/config.yaml
      response will be: {"message": "lol that works","code": 400}
    cmd: |
      grpcurl -plaintext -proto '_example/service.proto' \
        -d '{"message":"needed value"}' \
        {{.CLI_ARGS}} \
        localhost:8080 com.github.Semior001.groxy.example.mock.ExampleService/Stub

  stub-random-uuid:
    desc: make a request to the service and get a random UUID
    summary: |
      requires: task server CONFIG=_example/templating/config.yaml
      response will be: {"message": "<some random UUID>"}
    cmd: |
      grpcurl -plaintext -proto '_example/service.proto' \
        -d '{"message":"random"}' \
        {{.CLI_ARGS}} \
        localhost:8080 com.github.Semior001.groxy.example.mock.ExampleService/Stub

  stub-matcher:
    desc: make a request to the service with a value matcher, see summary for details
    summary: |
      requires: task server CONFIG=_example/templating/config.yaml
      mocker will wait for 2 seconds and the response will be: {"message": "10"}
    cmd: |
      grpcurl -plaintext -proto '_example/service.proto' \
        -d '{"message":"matcher","multiplier":5}' \
        {{.CLI_ARGS}} \
        localhost:8080 com.github.Semior001.groxy.example.mock.ExampleService/Stub

  stub-generic:
    desc: make a request to the service without any header or body, see summary for details
    summary: |
      requires: task server CONFIG=_example/nested-messages/config.yaml
      response will be: {"dependency": {"value": "some value"}}
    cmd: |
      grpcurl -plaintext -proto '_example/service.proto' \
        {{.CLI_ARGS}} \
        localhost:8080 com.github.Semior001.groxy.example.mock.ExampleService/Stub

  error:
    desc: make a request to a method that always returns an error
    summary: |
      requires: task server CONFIG=_example/error-responses/config.yaml
      status will be INVALID_ARGUMENT, response headers will contain "X-Request-Id: 123" and trailers
      will contain "Powered-By: groxy"
    cmd: |
      grpcurl -v -plaintext -proto '_example/service.proto' \
        {{.CLI_ARGS}} \
        localhost:8080 com.github.Semior001.groxy.example.mock.ExampleService/Error

  upstream:
    desc: make a request that will be passed to the upstream service
    summary: |
      requires: task server CONFIG=_example/upstream-forwarding/config.yaml
    cmd: |
      grpcurl -plaintext -use-reflection \
        {{.CLI_ARGS}} \
        localhost:8080 grpc_echo.v1.EchoService/Echo

  upstream-rewrite:
    desc: make a request that will be passed to the upstream service with a rewritten method
    summary: |
      requires: task server CONFIG=_example/uri-rewrite/config.yaml
    cmd: |
      grpcurl -plaintext -proto '_example/service.proto' \
        {{.CLI_ARGS}} \
        localhost:8080 com.github.Semior001.groxy.example.mock.ExampleService/SomeEchoMethod
