# https://taskfile.dev

version: '3'

tasks:
  stub-with-header:
    desc: >-
      make a request to stub method with header 'test: true', see summary for details
    summary: |
      response will be: {"message": "needed value received","code": 200}
    cmd: |
      grpcurl -plaintext -proto '_example/service.proto' \
        -H 'test: true' \
        -d '{"message":"needed value"}' \
        {{.CLI_ARGS}} \
        localhost:8080 com.github.Semior001.groxy.example.mock.ExampleService/Stub

  stub-without-body:
    desc: make a request to stub method without header, see summary for details
    summary: |
        response will be: {"message": "lol that works","code": 400}
    cmd: |
      grpcurl -plaintext -proto '_example/service.proto' \
        -d '{"message":"needed value"}' \
        {{.CLI_ARGS}} \
        localhost:8080 com.github.Semior001.groxy.example.mock.ExampleService/Stub

  stub-random-uuid:
    desc: make a request to the service and get a random UUID
    summary: |
      response will be: {"message": "<some random UUID>"}
    cmd: |
      grpcurl -plaintext -proto '_example/service.proto' \
        -d '{"message":"random"}' \
        {{.CLI_ARGS}} \
        localhost:8080 com.github.Semior001.groxy.example.mock.ExampleService/Stub

  stub-generic:
    desc: make a request to the service without any header or body, see summary for details
    summary: |
      response will be: {"dependency": {"value": "some value"}}
    cmd: |
      grpcurl -plaintext -proto '_example/service.proto' \
        {{.CLI_ARGS}} \
        localhost:8080 com.github.Semior001.groxy.example.mock.ExampleService/Stub

  error:
    desc: make a request to a method that always returns an error
    summary: |
      status will be INVALID_ARGUMENT, response headers will contain "X-Request-Id: 123" and trailers 
      will contain "Powered-By: groxy"
    cmd: |
      grpcurl -v -plaintext -proto '_example/service.proto' \
        {{.CLI_ARGS}} \
        localhost:8080 com.github.Semior001.groxy.example.mock.ExampleService/Error

  upstream:
    desc: make a request that will be passed to the upstream service, requires the upstream service to be running
    cmd: |
      grpcurl \
        -plaintext -proto '_example/service.proto' \
        {{.CLI_ARGS}} \
        localhost:8080 com.github.Semior001.groxy.example.mock.Upstream/Get